version: 2.1

# ORBS - Common functionality between projects

# COMMANDS - Common functionality between jobs

# JOBS - Common functionality between workflows, collection of commands / steps
jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      EXAMPLE_STATEMENT: HELLO WORLD STATEMENT!
      NODE_ENV: production
    steps:
      - checkout
      - run: echo ${EXAMPLE_STATEMENT}
  test:
    docker:
      - image: circleci/node:14
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run: npm install
      - run: npm run test

# WORKFLOWS
workflows:
  ready:
    jobs:
      - build:
          requires:
            - test
      - test
