version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      EXAMPLE_STATEMENT: HELLO WORLD STATEMENT!
      NODE_ENV: production
    steps:
      - checkout
      - run: echo ${EXAMPLE_STATEMENT}
  test:
    docker:
      - image: circleci/node:14
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run: npm install
      - run: npm run test

workflows:
  ready:
    jobs:
      - build:
          requires:
            - test
      - test
