version: 2.1

# ORBS - Common functionality between projects

# COMMANDS - Common functionality between jobs

# JOBS - Common functionality between workflows, collection of commands / steps
jobs:
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo 'Updaing PRODUCTION environment'

  release:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo 'Pushing code out into the world!'

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run test

# WORKFLOWS
workflows:
  release:
    jobs:
      - deploy:
          requires:
            - release
      - release:
          requires:
            - test
      - test
