version: 2.1

# ORBS - Common functionality between projects

# COMMANDS - Common functionality between jobs

# JOBS - Common functionality between workflows, collection of commands / steps
jobs:
  deploy-to-production:
    docker:
      - image: circleci/node:14
    environment:
      ENVIRONMENT: PRODUCTION
    steps:
      - checkout
      - run: echo 'Updaing ${ENVIRONMENT} environment'

  deploy-to-staging:
    docker:
      - image: circleci/node:14
    environment:
      ENVIRONMENT: STAGING
    steps:
      - checkout
      - run: echo 'Updaing ${ENVIRONMENT} environment'

  release-version:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: cd release && bash entrypoint.sh

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cd src && npm install
      - run: cd src && npm run test

# WORKFLOWS
workflows:
  build-and-deploy:
    jobs:
      - deploy-to-production:
          filters:
            branches:
              only: master
          requires:
            - test

      - deploy-to-staging:
          filters:
            branches:
              only: development
          requires:
              - release-version
              - test

      - release-version:
          filters:
            branches:
              only: development
          requires:
            - test

      - test
