version: 2.1

# ORBS - Common functionality between projects

# COMMANDS - Common functionality between jobs

# JOBS - Common functionality between workflows, collection of commands / steps
jobs:
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo 'Updaing PRODUCTION environment'

  release:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout:
          path: ~/release
      - run: bash entrypoint.sh

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout:
          path: ~/src
      - run: npm install
      - run: npm run test

# WORKFLOWS
workflows:
  update-production:
    jobs:
      - deploy:
          requires:
            - release
      - release:
          requires:
            - test
      - test
