version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      EXAMPLE_STATEMENT: "HELLO WORLD STATEMENT!"
    steps:
      - checkout
      - run: echo ${EXAMPLE_STATEMENT}
